=== Rosshambo/JSUDiSH/Documentation/Google Group Files/experiment.xsd
<?xml version="1.0"?>

<xs:schema xmlns="http://www.jsu.edu" 
		   targetNamespace="http://www.jsu.edu" 
		   xmlns:xs="http://www.w3.org/2001/XMLSchema" 
		   elementFormDefault="qualified">


<xs:element name="da">
	<xs:complexType>
		<xs:all>
			<xs:element name="rewardType" type="xs:string"/>
			<xs:element name="daMinReward" type="minReward"/>
			<xs:element name="daMaxReward" type="maxReward"/>
			<xs:element name="maxTime" type="timeType"/>
			<xs:element name="responseDelay" type="timeType"/>
			<xs:element name="numTrials" type="xs:integer"/>
			<xs:element name="daInstructions" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="soonerTime" type="timeType"/>
			<xs:element name="laterTime" type="timeType"/>
			<xs:element name="doubleDelay" type="timeType"/>
			<xs:element name="intertrialInterval" type="timeType"/>
		</xs:all>
	</xs:complexType>					
</xs:element>

<xs:element name="dl">
	<xs:complexType>
		<xs:all>
			<xs:element name="rewardType" type="xs:string"/>
			<xs:element name="dlMinReward" type="minReward"/>
			<xs:element name="dlMaxReward" type="maxReward"/>
			<xs:element name="maxTime" type="timeType"/>
			<xs:element name="responseDelay" type="timeType"/>
			<xs:element name="dlInstructions" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="soonerTime" type="timeType"/>
			<xs:element name="laterTime" type="timeType"/>
			<xs:element name="doubleDelay" type="timeType"/>
			<xs:element name="intertrialInterval" type="timeType"/>
		</xs:all>
	</xs:complexType>					
</xs:element>

<xs:element name="experiment">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="personnel"/>
			<xs:element name="title" type="xs:string"/>
			<xs:element name="number" type="xs:integer" default="1"/>
			<xs:element name="instructions" type="xs:string"/>
			<xs:element ref="methods"/>
			<xs:element name="conclusion" type="xs:string"/>
		</xs:sequence>			
	</xs:complexType>
</xs:element>

<xs:element name="investigator">
	<xs:complexType>
		<xs:all>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="department" type="xs:string"/>
		</xs:all>
	</xs:complexType>
</xs:element>

<xs:element name="mc">
	<xs:complexType>
		<xs:all>
			<xs:element name="rewardType" type="xs:string"/>
			<xs:element name="mcMinReward" type="minReward"/>
			<xs:element name="mcMaxReward" type="maxReward"/>
			<xs:element name="maxTime" type="timeType"/>
			<xs:element name="responseDelay" type="timeType"/>
			<xs:element name="distribution" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element ref="scenario" minOccurs="1" maxOccurs="1"/>
			<xs:element name="mcInstructions" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="soonerTime" type="timeType"/>
			<xs:element name="laterTime" type="timeType"/>
			<xs:element name="timeUnits" type="timeType"/>
			<xs:element name="choiceList" type="xs:string"/>
			<xs:element name="intertrialInterval" type="timeType"/>
		</xs:all>
	</xs:complexType>					
</xs:element>

<xs:element name="methods">
	<xs:complexType>
		<xs:choice maxOccurs="unbounded">
			<xs:element ref="da" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element ref="dl" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element ref="mc" minOccurs="0" maxOccurs="unbounded"/>
		</xs:choice>
	</xs:complexType>
</xs:element>

<xs:element name="option">
	<xs:complexType>
		<xs:all>
			<xs:element name="reward" type="xs:decimal"/>
			<xs:element name="time" type="timeType"/>
		</xs:all>
	</xs:complexType>
</xs:element>

<xs:element name="personnel">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="investigator" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:element name="scenario">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="option" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>					
</xs:element>

<xs:complexType name="timeType">
	<xs:simpleContent>
		<xs:extension base="xs:decimal">
			<xs:attribute name="units" type="timeUnits" />
		</xs:extension>
	</xs:simpleContent>
</xs:complexType>

<xs:simpleType name="timeUnits">
	<xs:restriction base="xs:string">
		<xs:enumeration value="seconds"/>
		<xs:enumeration value="minutes"/>
		<xs:enumeration value="hours"/>
		<xs:enumeration value="days"/>
		<xs:enumeration value="weeks"/>
		<xs:enumeration value="months"/>
		<xs:enumeration value="years"/>
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="minReward">
		<xs:restriction base="xs:decimal">
			<xs:totalDigits value= "75"/>
			<xs:fractionDigits value="4"/>
		</xs:restriction>
</xs:simpleType>
<xs:simpleType name="maxReward">
		<xs:restriction base="xs:decimal">
			<xs:totalDigits value="75"/>
			<xs:fractionDigits value="4"/>
		</xs:restriction>
</xs:simpleType>

</xs:schema>

=== Rosshambo/JSUDiSH/Documentation/Google Group Files/experiment.xml
<?xml version="1.0" encoding="utf-8"?>
<experiment xmlns="http://www.jsu.edu" 
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
			xsi:schemaLocation="http://www.jsu.edu experiment.xsd">
  <personnel>
    <investigator>
      <name> Heidi Dempsey </name>
      <department> Psychology </department>
    </investigator>
    <investigator>
      <name> David Dempsey </name>
      <department> Mathematics </department>
    </investigator>
    <investigator>
      <name> Aaron Garrett </name>
      <department> Computer Science </department>
    </investigator>
  </personnel>
  <title> Discounting in Study Habits Experiment </title>
  <number> 1 </number>
  <instructions>
	All the instructions should go here and will be placed in the interface.
  </instructions>
  <methods>
    <!-- There are 3 different possibilities (right now) for the experiment methods: dl (double limit), da (decreasing adjustment), and mc (multiple choice). -->
    <!-- Each of these can be placed as many times and in any order that you choose. -->
    <!-- The time variables (maxTime and responseDelay) have an optional attribute called "units" that can be set to any of the following values: -->
    <!-- "seconds", "minutes", "hours", "days", "weeks", "months", or "years" -->
    <!-- The default value is "seconds" if it is left unspecified. -->
    <da>
      <rewardType> point </rewardType>
      <daMinReward> 0.5 </daMinReward>
      <daMaxReward> 10 </daMaxReward>
      <maxTime units="minutes"> 2 </maxTime>
      <responseDelay> 1 </responseDelay>
      <numTrials> 5 </numTrials>
	  <daInstructions> Choose one option </daInstructions>
	  <soonerTime> 0 </soonerTime>
	  <laterTime> 0 </laterTime>
	  <doubleDelay> 0 </doubleDelay>
	  <intertrialInterval> 0 </intertrialInterval>
    </da>
	
    <dl>
      <rewardType> vacation </rewardType>
      <dlMinReward> 0.5 </dlMinReward>
      <dlMaxReward> 10 </dlMaxReward>
      <maxTime units="minutes"> 2 </maxTime>
      <responseDelay units="seconds"> 0 </responseDelay>
	  <dlInstructions> Choose one option </dlInstructions>
	  <soonerTime> 0 </soonerTime>
	  <laterTime> 0 </laterTime>
	  <doubleDelay> 0 </doubleDelay>
	  <intertrialInterval> 0 </intertrialInterval>
	</dl>
    <mc>
      <rewardType> dollar </rewardType>
      <mcMinReward> 0.5 </mcMinReward>
      <mcMaxReward> 10 </mcMaxReward>
      <maxTime units="minutes"> 2 </maxTime>
      <responseDelay units="seconds"> 1 </responseDelay>
	  <distribution> Exponential </distribution>
      <scenario>
        <option>
          <reward> 0.01 </reward>
          <time> 0 </time>
        </option>
        <option>
          <reward> 0.5 </reward>
          <time units="seconds"> 30 </time>
        </option>
        <option>
          <reward> 1 </reward>
          <time> 60 </time>
        </option>
      </scenario>
	  <mcInstructions> Choose one option </mcInstructions>
	  <soonerTime> 0 </soonerTime>
	  <laterTime> 0 </laterTime>
	  <timeUnits> 0 </timeUnits>
	  <choiceList> apples </choiceList>
	  <intertrialInterval> 0 </intertrialInterval>
    </mc>
    <mc>
      <rewardType> ice cream </rewardType>
      <mcMinReward> 1 </mcMinReward>
      <mcMaxReward> 15 </mcMaxReward>
      <maxTime units="minutes"> 2 </maxTime>
      <responseDelay units="seconds"> 2 </responseDelay>
      <distribution> Logarithmic </distribution>
      <scenario>
        <option>
          <reward> 0.1 </reward>
          <time> 0 </time>
        </option>
        <option>
          <reward> 0.25 </reward>
          <time units="seconds"> 10 </time>
        </option>
        <option>
          <reward> 1 </reward>
          <time> 30 </time>
        </option>
      </scenario>
	  <mcInstructions> Choose one option </mcInstructions>
	  <soonerTime> 0 </soonerTime>
	  <laterTime> 0 </laterTime>
	  <timeUnits> 0 </timeUnits>
	  <choiceList> apples </choiceList>
	  <intertrialInterval> 0 </intertrialInterval>
    </mc>
  </methods>
  <conclusion>
	Final concluding remarks will go here and will be displayed at the end of the experiment.
  </conclusion>
</experiment>
